# Mutation
mutation CreatePost($createPost: CreatePostInput!) {
  createPost(createPostInput: $createPost) {
    post {
      id
      title
      content
      tag
      description
      publishedAt
      isActive
      author {
        id
        name
        email
        phone
      }
    }
  }
}

# Variables
{
  "createPost": {
    "title": "This is my first post",
    "content": "Test post.",
    "category": "social",
    "description": null
  }
}