# Mutation
mutation InactivePost($inactivePost: InactivePostInput!) {
	inactivePost(activePostInput: $inactivePost)
}

# Variables
{
	"inactivePost": {
		"postId": "93206607-902c-4e0d-82ba-369f6add64e3"
	}
}