# Query
query ListPosts($listPosts: ListPostsInput) {
  listPosts(listPostsInput: $listPosts) {
    posts {
      id
      title
      content
      description
      tag
      category
      publishedAt
      isActive
      author {
        id
        name
        email
        phone
      }
    }
  }
}

# Variables
{
  "listPosts": {
    "authorIdEquals": "d9219023-17e9-4c86-a2b6-4071d5caa85e",
    "categoryEquals": "games",
    "publish": true,
    "tagEquals": "this-is-my-first-post",
    "titleContains": "This is my first post"
  }
}