# Mutation
mutation PublishPost($publishPost: PublishPostInput!) {
  publishPost(publishPostInput: $publishPost)
}

# Variables
{
  "publishPost": {
    "postId": "6651950e-f277-4f0b-9bd8-69a3e2646007"
  }
}