# Mutation
mutation UpdatePost($updatePost: UpdatePostInput!) {
  updatePost(updatePostInput: $updatePost) {
    post {
      id
      title
      content
      description
      tag
      category
      publishedAt
      author {
        id
        name
        email
        phone
      }
    }
  }
}

# Variables
{
  "updatePost": {
    "postId": "6651950e-f277-4f0b-9bd8-69a3e2646007",
    "title": "This is my first post",
    "content": "Test content post.",
    "category": "games",
    "description": "Test description post."
  }
}