# Query
query ListAuthors($listAuthors: ListAuthorsInput) {
  listAuthors(listAuthorsInput: $listAuthors) {
    authors {
      id
      name
      email
      phone
      posts {
        id
        title
        content
        description
        tag
        category
        publishedAt
      }
    }
  }
}

# Variables
{
  "listAuthors": {
    "nameContains": "author",
    "emailContains": "author"
  }
}