# Query
query ShowAuthor {
  showAuthor {
    author {
      id
      name
      email
      phone
      posts {
        id
        title
        content
        description
        tag
        category
        publishedAt
        isActive
      }
    }
  }
}
