# Mutation
mutation UpdateAuthor($updateAuthor: UpdateAuthorInput!) {
  updateAuthor(updateAuthorInput: $updateAuthor) {
    author {
      id
      name
      phone
      email
      posts {
        id
        title
        content
        description
        tag
        category
        publishedAt
      }
    }
  }
}

# Variables
{
  "updateAuthor": {
    "name": "Author test",
    "email": "author.test@mail.com.br",
    "phone": "12345678",
    "password": "Strong-password"
  }
}